mysite/articles/urls.py
from django.urls import path
# 밑의 . 은 내 현재 폴더를 의미한다.
from . import views
app_name = "articles"
# 경로에 이름을 지정해준 이유: 어디로 이동해야 되는지를 
# 수정해줘야 될 때 이 이름을 통해서 수정할 수 있도록 해주기 위해서이다.
urlpatterns = [
    # path('index/', views.index, name="index"),
    path('', views.index, name="index"),
    path('new/', views.new, name="new"),
    path('create/', views.create, name="create"),
    path('introduce/', views.introduce, name="introduce"),
    path('detail/<int:article_pk>/', views.detail, name="detail"),
    path('<int:article_pk>/delete/', views.delete, name="delete"),
    path('<int:article_pk>/edit/', views.edit, name="edit"),
    path('<int:article_pk>/update/', views.update, name="update"),
]

mysite/jobs/urls.py
from django.urls import path
# 밑의 . 은 내 현재 폴더를 의미한다.
from . import views
app_name = "jobs"

urlpatterns = [
    path('', views.index, name="index"),
    path('past_life/', views.past_life, name="past_life"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('jobs/', include('jobs.urls')),
]

mysite/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model) : 
    # articles_article
    title = models.CharField(max_length=150)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    # 수정이 되는 시간을 저장해준다.
    updated_at = models.DateTimeField(auto_now=True)
    # 원래 있던 매직 메서드를 오버라이딩 한 것
    def __str__(self):
        return f'{self.id}번째글 - {self.title} : {self.content}'

    # 원래 있던 쿼리를 조작하는 것은 추천하지 않는다.

mysite/jobs/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
    # persons_person
    name = models.CharField(max_length=150)
    pastjob = models.TextField()
    
    def __str__(self):
        return f'{self.id} - {self.name} : {self.pastjob}'

mysite/articles/views.py
from django.shortcuts import render, redirect
# 모델 가져오기
from .models import Article

# Create your views here.
# 이름을 정확하게 구분하게 하기 위해서 app_name 폴더를 생성해주고
def index(request):
    # 전체 데이터 가져오기
    # articles = Article.objects.all().order_by('-pk')
    articles = Article.objects.all()[::-1]
    # 그 데이터 템플릿에게 넘겨주기
    context = {
        'articles' : articles
    }
    # 템플릿에서 반복문으로 각각의 게시글을
    # pk, title 보여주기
    return render(request, 'articles/index.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    # GET 방식은 DB 변화 없이 쿼리 요청을 보낼 때 사용한다.
    # title = request.GET.get('title')
    # content = request.GET.get('content')
    title = request.POST.get('title')
    content = request.POST.get('content')
    # 데이터 생성을 위한 ORM 활용
    # 첫 번째 방법
    # article = Article()
    # article.title = title
    # article.content = content
    # article.save
    # 두 번째 방법
    article = Article(title=title, content=content)
    article.save()
    # 세 번째 방법
    # Article.objects.create(title=title, content=content)
    # 어떤 방식을 사용 했는가에 따라서
    # save() 메서드를 사용 할 것인지 아닌지
    # articles = Article(title=title, content=content)
    # articles.save()
    # context = {
    #     'title' : title,
    #     'content' : content
    # }
    # return render(request, 'articles/create.html', context)
    return redirect('articles:index')

# 1. 상세페이지를 보기위한 경로
# 1-1. 특정 게시글에 대한 고유 값
# 1-2. /articles/1/, /articles/2/
# 2. 해당 게시글에 대한 상세 내용
# 2-1. 게시글의 pk, title, ...
# 3. 인덱스 페이지로 돌아가는 링크
def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    context = {
        'article' : article
    }
    return render(request, 'articles/detail.html', context)

# 1. 특정 글 삭제를 위한 경로 작성
# 1-1. /articles/1/delete/
# 2. 글 삭제 처리를 해주는 view 작성
# 3. 글 삭제 후, index page로 redirect
# 4. 글 삭제를 위한 링크 detail에 작성
def delete(request, article_pk):
    # request.method()
    article = Article.objects.get(pk=article_pk)
    if request.method == "POST":
        article.delete()
        return redirect('articles:index')
    # Article.objects.filter(pk=article_pk).delete()
    return redirect('articles:detail', article.pk)

# edit
# 1. 특정 글 수정을 위한 경로 설정
# 1-1. /articles/1/edit/
# 2. 글 수정 template를 render하는 edit view 작성
# 2-1. 해당 template에 form tag 작성
# 2-2. 각 input tag 내부에 기존 내용이 들어있어야 함.
# 2-3. value 속성을 활용 하시면 됩니다.
def edit(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    context = {
        'article' : article
    }
    return render(request, 'articles/edit.html', context)
# update
# 3. edit에서 보낸 데이터 처리를 위한 경로 생성
# 3-1. /articles/1/update/
# 4. 글 수정 처리를 하는 update view 작성
# 5. 해당 글 상세 페이지로 redirect
# 6. 글 수정을 위한 edit 링크 상세 페이지에 생성
# 6-1. {% url 'articles:edit' article.pk %}
def update(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    title = request.POST.get('title')
    content = request.POST.get('content')
    article.title = title
    article.content = content
    article.save()
    return redirect('articles:detail', article_pk)
# 1. /introduce/
# 2. h1 태그로 이루어진 제목
# 2-1. 각각의 p 태그에 이름과 나이 작성
# 3. back 링크로 index로 돌아갈 수 있는 링크 하나
# 4. index에서 introduce로 이동할 수 있는 링크 하나
# 5. base.html 상속받아서 block body 안에 작성
# etc. 작성 완료 하신 분들은

def introduce(request):
    return render(request, 'articles/introduce.html')

mysite/jobs/views.py
from django.shortcuts import render, redirect
from .models import Person
import random
# Create your views here.
def index(request):
    persons = Person.objects.all()[::-1]
    context = {
        'persons' : persons
    }
    return render(request, 'jobs/index.html', context)

def past_life(request):
    
    job_past = ['관리자', '군인', '관리자', '국회의원', '지방의회의원', '중앙정부 고위공무원', '대표이사', 
    '게임 프로그래머', '비디오 게임 기획자', '건축가', '항공기 조종사', '항공기관사', '선장', '항해사', 
    '도선사', '관제사', '전문 의사', '일반 의사', '한의사', '치과 의사', '수의사', '약사', '한약사', 
    '간호사', '보건 교사', '영양사', '영양 교사', '임상병리사', '방사선사', '치과기공사', '치과위생사', 
    '물리치료사', '작업치료사', '정신보건 임상심리사', '언어치료사', '안경사', '보건의료정보관리사', 
    '간호조무사', '사회복지사', '청소년 지도사', '목사', '신부', '승려', '교무', '수녀 및 수사', '전도사', 
    '대학 교수', '대학 시간강사', '학교 교사', '국어 교사', '수학 교사', '사회 교사', '과학 교사', '음악교사', 
    '미술교사', '체육교사', '가정 교사', '영어교사', '초등학교 교사', '특수교육 교사', '장학사', '대학 교육조교', 
    '판사', '검사', '변호사', '법무사', '집행관', '변리사', '노무사', '회계사', '세무사', '관세사', 
    '투자 및 금융 분석가', '신용 분석가', '보험계리사', '손해사정인', '감정평가사', '감정사', '소믈리에', '조향사',
    '부동산 중개인', '방송작가', '작가', '평론가', '시인', '소설가', '영화 평론가', '각본가', '번역가', '통역가', 
    '기자', '큐레이터', '사서', '감독', '배우', '개그맨', '코미디언', '모델', '패션 모델', '성우', '스턴트맨',
    '보조출연자', '아나운서', '리포터', '쇼핑호스트', '비디오자키', '디스크자키', '화가', '조각가', '사진가',
    '만화가', '만화영화 작가', '국악인', '지휘자', '작곡가', '가수', '성악가', '안무가', '디자이너', '제품 디자이너',
    '자동차 디자이너', '패션 디자이너', '인테리어 디자이너', '무대 및 세트 디자이너', '시각 디자이너', '북 디자이너',
    '삽화가', '활자 디자이너', '웹 디자이너', '게임그래픽 디자이너', '경기감독 및 코치', '직업 운동선수', '경기심판',
    '트레이너', '수영강사', '바둑기사', '프로게이머', '연예인 및 스포츠 매니저', '마술사', '곡예사', '조련사', '비서',
    '법무 사무원', '속기사', '경찰관', '소방관', '교도관', '경호원', '간병인', '미용사', '장의사', '점술가', '무당',
    '항공기 객실승무원', '관광 통역 안내원', '카지노 딜러', '골프장 캐디', '응원단원', '주방장', '조리사', '요리사',
    '커피 조리사', '바텐더', '웨이터', '보험 설계사', '텔레마케터', '작물재배 종사자', '양치기', '수렵 종사원',
    '동물 사육사', '벌목원', '어부', '해녀', '제빵원', '제과원', '도축원', '단조원', '항공기 정비원', '광원', '배관공',
    '원자력발전장치 운전원', '철도 및 전동차 기관사', '택시 운전원', '버스 운전원', '화물차 및 특수차 운전원',
    '선박 갑판승무원 및 관련 종사원', '건설 단순 종사원', '배달원', '우편물 집배원', '환경 미화원', '경비원',
    '가사 도우미', '육아 도우미', '패스트푸드원', '주유원', '전단지 배포원 및 벽보원', '목동', '주차 안내원', '군인',
    '장교', '장기 부사관', '준위']
    name = request.POST.get('username')
    pastjob = random.choice(job_past)
    print("*"*30)
    print(name)
    print(pastjob)
    print("*"*30)
    person = Person.objects.filter(name=name)
    print(len(person))
    if len(person) != 0:
        person = person[0]
    else: # len(name) == 0:
        person = Person()
        person.name = name
        person.pastjob = pastjob
        person.save()
    context = {
        'person' : person
    }
    return render(request, 'jobs/past_life.html', context)

mysite/articles/templates/articles/create.html
{% extends 'base.html' %}
{% block body %}
<h1>글 작성 완료</h1>
<hr>
<h2>제목: {{ title }}</h2>
<p>본문: {{ content }}</p>
<hr>
<a href="{% url 'articles:index' %}" target="_self">back</a>
{% endblock %}

mysite/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block body %}
<h1>게시글 상세 페이지</h1>
<hr>
<h3>{{article.pk}}번째 글</h3>
<p>제목: {{ article.title }}</p>
<p>내용: {{ article.content }}</p>
<p>생성 시간: {{ article.created_at }}</p>
<p>수정 시간: {{ article.updated_at }}</p>
<hr>
<form action="{% url 'articles:delete' article.pk %}" method="POST">
  {% csrf_token %}
  <input type="submit" value="[DELETE]">
</form>
<a href="{% url 'articles:index' %}" target="_self">[back]</a>
&nbsp;
<!-- <a href="/articles/{{article.pk}}/delete/">[delete1]</a> -->
<a href="{% url 'articles:delete' article.pk %}">[delete]</a>
&nbsp;
<a href="{% url 'articles:edit' article.pk %}">[edit]</a>
{% endblock %}

mysite/articles/templates/articles/edit.html
{% extends 'base.html' %}
{% block body %}
<h1>글 수정 페이지</h1>
<hr>
<form action="{% url 'articles:update' article.pk %}" method="POST">
  <!-- GET에서 POST로 변경하는 방법 method = "POST" -->
  <!-- CSRF 사이트 간 요청 위조  -->
  {% csrf_token %}
  <label for="name">수정 제목 : </label>
  <input type="text" name="title" id="name" value="{{articles.title}}">
  <br/>
  <label for="cnt">수정 내용 : </label>
  <textarea type="text" name="content" rows="10" cols="50"  id="cnt">
  {{ article.content }}
  </textarea>
  <br/>
  <input type="submit" value="글 수정 작성">
</form>
{% endblock %}

mysite/articles/templates/articles/index.html
{% extends 'base.html'%}
{% block body %}
  <h1>게시판</h1>
  <hr>
  <a href="{% url 'articles:new' %}">NEW</a>
  &nbsp;
  <a href="{% url 'articles:introduce' %}">Introduce</a>
  <hr>
  <!-- 여기에 작성할 것 -->
  {% for article in articles %}
    <h3>{{ article.pk }}번째 글</h3>
    <p>제목 : {{ article.title }}</p>
    <a href="{% url 'articles:detail' article.pk %}" target="_self">[Detail]</a>
    <!-- <a href="/articles/detail/{{article.pk}}/">[Detail]</a> -->
    <hr>
  {% endfor %}
{% endblock %}

mysite/articles/templates/articles/introduce.html
{% extends 'base.html' %}
{% block body %}
<h1>소개 페이지</h1>
<hr>
<p>나의 이름 : 이준성</p>
<p>나의 나이 : 100</p>
<hr>
<a href="{% url 'articles:index' %}">back</a>
{% endblock %}

mysite/articles/templates/articles/new.html
{% extends 'base.html' %}
{% block body %}
<h1>글 작성 페이지</h1>
<form action="{% url 'articles:create' %}" method="POST">
  <!-- GET에서 POST로 변경하는 방법 method = "POST" -->
  <!-- CSRF 사이트 간 요청 위조  -->
  {% csrf_token %}
  <label for="name">제목 : </label>
  <input type="text" name="title" id="name" placeholder="여기에 제목을 입력해주세요.">
  <br/>
  <label for="cnt">내용 : </label>
  <textarea type="text" name="content" rows="10" cols="50"  id="cnt">
  여기에 내용을 입력해 주세요.
  </textarea>
  <br/>
  <input type="submit" value="제출">
</form>
{% endblock %}

mysite/jobs/templates/jobs/index.html
{% extends 'base.html' %}
{% block body %}
<h3>[전생 직업 파악 페이지]</h3>
<form action="{% url 'jobs:past_life' %}" method="POST">
  <!-- GET에서 POST로 변경하는 방법 method = "POST" -->
  <!-- CSRF 사이트 간 요청 위조  -->
  {% csrf_token %}
  <label for="name">사용자 이름 : </label>
  <input type="text" name="username" id="name" placeholder="여기에 이름을 입력해주세요.">
  <br/>
  <div class="form-label-group">
  <input type="submit" value="전생 직업 검색">
  </div>
</form>
{% for person in persons %}
  <h3> 이름: {{person.name}}
  <h3> 전생직업: {{person.pastjob}}
{% endfor %}
{% endblock %}

mysite/jobs/templates/jobs/past_life.html
{% extends 'base.html' %}
{% block body %}

<h1> 전생 직업 예측 결과</h1>
<hr>
<h3>{{ person.name }}님의 전생은 {{ person.pastjob }}입니다.</h3>
<a href="{% url 'jobs:index' %}">back</a>
{% endblock %}

mysite/mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <title>
    {% block title %}
      마이 사이트
    {% endblock %}
  </title>
</head>
<body>
  <div class="container">
    {% block body %}
    
    {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>